/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yourpackage_Jenkins */

#ifndef _Included_com_yourpackage_Jenkins
#define _Included_com_yourpackage_Jenkins
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yourpackage_Jenkins
 * Method:    nativeTcpSynFlood
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yourpackage_Jenkins_nativeTcpSynFlood
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
